import { ApolloClient, InMemoryCache } from '@apollo/client';
import Head from 'next/head';
import Link from 'next/link';
import { GET_ALL_POSTS } from '../graphql/queries';

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>The Recipe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3 className='title'>All Recipes</h3>
        <div className='card-container'>
          {posts.map((post, index) => (
            <div key={index} className='card'>
              <div className='image'>
                <img src={post.attributes.imageUrl} />
              </div>
              <div className='text'>
                <h3>{post.attributes.title}</h3>
                <p>{post.attributes.description}</p>
                <Link href={post.attributes.urlSlug}>Continue Reading &rarr;</Link>
              </div>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: process.env.APP_URI,
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: GET_ALL_POSTS
  });

  return {
    props: {
      posts: data.blogPosts.data
    },
    revalidate: 10
  }
}